print("=====GEBYAR DISKON=====")
print("=====MASUKKAN JUMLAH BARANG YANG DIPESAN=====")
k=int(input("TOTAL KIPAS ANGIN DISKON 10%  Rp 25.000,00  :"))
s=int(input("TOTAL SEPEDA DISKON 55%       Rp 6.000,00   :"))
h=int(input("TOTAL HELM ROSSI DISKON 77%   Rp 8.000,00   :"))
print("=====TOTAL=====")
x=((25000*k)*(10/100))
y=((6000*s)*(55/100))
z=((8000*h)*(77/100))
str(print("TOTAL KIPAS ANGIN                    :",(x)))
str(print("TOTAL SEPEDA MOTOR                   :",(y)))
str(print("TOTAL HELM ROSSI                     :",(z)))
print("Jumlah total diskon yang didapat adalah",(x+y+z))